//#line 2 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the heiman package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __heiman__GETALLFROMHTPAPUBLISHEDCONFIG_H__
#define __heiman__GETALLFROMHTPAPUBLISHEDCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace heiman
{
  class getallfromHTPApublishedConfigStatics;
  
  class getallfromHTPApublishedConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(getallfromHTPApublishedConfig &config, const getallfromHTPApublishedConfig &max, const getallfromHTPApublishedConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const getallfromHTPApublishedConfig &config1, const getallfromHTPApublishedConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, getallfromHTPApublishedConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const getallfromHTPApublishedConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, getallfromHTPApublishedConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const getallfromHTPApublishedConfig &config) const = 0;
      virtual void getValue(const getallfromHTPApublishedConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T getallfromHTPApublishedConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (getallfromHTPApublishedConfig::* field);

      virtual void clamp(getallfromHTPApublishedConfig &config, const getallfromHTPApublishedConfig &max, const getallfromHTPApublishedConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const getallfromHTPApublishedConfig &config1, const getallfromHTPApublishedConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, getallfromHTPApublishedConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const getallfromHTPApublishedConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, getallfromHTPApublishedConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const getallfromHTPApublishedConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const getallfromHTPApublishedConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, getallfromHTPApublishedConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); i++)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;
        
        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }
      
      virtual void updateParams(boost::any &cfg, getallfromHTPApublishedConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++) 
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); i++)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<getallfromHTPApublishedConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(getallfromHTPApublishedConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = params.begin(); i != params.end(); i++)
      {
        boost::any val;
        (*i)->getValue(config, val);

        if("temperatura_mean"==(*i)->name){temperatura_mean = boost::any_cast<double>(val);}
        if("temperatura_stddev"==(*i)->name){temperatura_stddev = boost::any_cast<double>(val);}
        if("lower_temp_limit"==(*i)->name){lower_temp_limit = boost::any_cast<double>(val);}
        if("upper_temp_limit"==(*i)->name){upper_temp_limit = boost::any_cast<double>(val);}
        if("zoom_temp"==(*i)->name){zoom_temp = boost::any_cast<int>(val);}
        if("threshold_temp"==(*i)->name){threshold_temp = boost::any_cast<int>(val);}
        if("min_size_temp"==(*i)->name){min_size_temp = boost::any_cast<int>(val);}
        if("max_size_temp"==(*i)->name){max_size_temp = boost::any_cast<int>(val);}
        if("lower_evidence_limit"==(*i)->name){lower_evidence_limit = boost::any_cast<double>(val);}
        if("upper_evidence_limit"==(*i)->name){upper_evidence_limit = boost::any_cast<double>(val);}
        if("zoom_evidence"==(*i)->name){zoom_evidence = boost::any_cast<int>(val);}
        if("threshold_evidence"==(*i)->name){threshold_evidence = boost::any_cast<double>(val);}
        if("min_size_evidence"==(*i)->name){min_size_evidence = boost::any_cast<int>(val);}
        if("max_size_evidence"==(*i)->name){max_size_evidence = boost::any_cast<int>(val);}
      }
    }

    double temperatura_mean;
double temperatura_stddev;
double lower_temp_limit;
double upper_temp_limit;
int zoom_temp;
int threshold_temp;
int min_size_temp;
int max_size_temp;
double lower_evidence_limit;
double upper_evidence_limit;
int zoom_evidence;
double threshold_evidence;
int min_size_evidence;
int max_size_evidence;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double temperatura_mean;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double temperatura_stddev;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double lower_temp_limit;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double upper_temp_limit;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int zoom_temp;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int threshold_temp;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int min_size_temp;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int max_size_temp;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double lower_evidence_limit;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double upper_evidence_limit;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int zoom_evidence;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double threshold_evidence;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int min_size_evidence;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int max_size_evidence;
//#line 255 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("getallfromHTPApublishedConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const getallfromHTPApublishedConfig &__max__ = __getMax__();
      const getallfromHTPApublishedConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const getallfromHTPApublishedConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const getallfromHTPApublishedConfig &__getDefault__();
    static const getallfromHTPApublishedConfig &__getMax__();
    static const getallfromHTPApublishedConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const getallfromHTPApublishedConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void getallfromHTPApublishedConfig::ParamDescription<std::string>::clamp(getallfromHTPApublishedConfig &config, const getallfromHTPApublishedConfig &max, const getallfromHTPApublishedConfig &min) const
  {
    return;
  }

  class getallfromHTPApublishedConfigStatics
  {
    friend class getallfromHTPApublishedConfig;
    
    getallfromHTPApublishedConfigStatics()
    {
getallfromHTPApublishedConfig::GroupDescription<getallfromHTPApublishedConfig::DEFAULT, getallfromHTPApublishedConfig> Default("Default", "", 0, 0, true, &getallfromHTPApublishedConfig::groups);
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.temperatura_mean = -100.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.temperatura_mean = 200.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.temperatura_mean = 32.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("temperatura_mean", "double", 0, "Media de la temperatura", "", &getallfromHTPApublishedConfig::temperatura_mean)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("temperatura_mean", "double", 0, "Media de la temperatura", "", &getallfromHTPApublishedConfig::temperatura_mean)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.temperatura_stddev = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.temperatura_stddev = 10.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.temperatura_stddev = 2.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("temperatura_stddev", "double", 0, "Desviacion estandar de la temperatura", "", &getallfromHTPApublishedConfig::temperatura_stddev)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("temperatura_stddev", "double", 0, "Desviacion estandar de la temperatura", "", &getallfromHTPApublishedConfig::temperatura_stddev)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.lower_temp_limit = -100.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.lower_temp_limit = 200.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.lower_temp_limit = 25.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("lower_temp_limit", "double", 0, "Limite inferior de la temperatura (en Celsius)", "", &getallfromHTPApublishedConfig::lower_temp_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("lower_temp_limit", "double", 0, "Limite inferior de la temperatura (en Celsius)", "", &getallfromHTPApublishedConfig::lower_temp_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.upper_temp_limit = -100.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.upper_temp_limit = 200.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.upper_temp_limit = 45.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("upper_temp_limit", "double", 0, "Limite superior de la temperatura (en Celsius)", "", &getallfromHTPApublishedConfig::upper_temp_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("upper_temp_limit", "double", 0, "Limite superior de la temperatura (en Celsius)", "", &getallfromHTPApublishedConfig::upper_temp_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.zoom_temp = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.zoom_temp = 100;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.zoom_temp = 20;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("zoom_temp", "int", 0, "Zoom de la imagen de temperaturas", "", &getallfromHTPApublishedConfig::zoom_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("zoom_temp", "int", 0, "Zoom de la imagen de temperaturas", "", &getallfromHTPApublishedConfig::zoom_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.threshold_temp = -100;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.threshold_temp = 200;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.threshold_temp = 32;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("threshold_temp", "int", 0, "Threshold de las temperaturas (en Celsius)", "", &getallfromHTPApublishedConfig::threshold_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("threshold_temp", "int", 0, "Threshold de las temperaturas (en Celsius)", "", &getallfromHTPApublishedConfig::threshold_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.min_size_temp = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.min_size_temp = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.min_size_temp = 2000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("min_size_temp", "int", 0, "Tamanyo minimo del blob de las temperaturas", "", &getallfromHTPApublishedConfig::min_size_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("min_size_temp", "int", 0, "Tamanyo minimo del blob de las temperaturas", "", &getallfromHTPApublishedConfig::min_size_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_size_temp = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_size_temp = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_size_temp = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("max_size_temp", "int", 0, "Tamanyo maximo del blob de las temperaturas", "", &getallfromHTPApublishedConfig::max_size_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("max_size_temp", "int", 0, "Tamanyo maximo del blob de las temperaturas", "", &getallfromHTPApublishedConfig::max_size_temp)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.lower_evidence_limit = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.lower_evidence_limit = 1.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.lower_evidence_limit = 0.5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("lower_evidence_limit", "double", 0, "Limite inferior de la evidencia (entre 0 y 1)", "", &getallfromHTPApublishedConfig::lower_evidence_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("lower_evidence_limit", "double", 0, "Limite inferior de la evidencia (entre 0 y 1)", "", &getallfromHTPApublishedConfig::lower_evidence_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.upper_evidence_limit = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.upper_evidence_limit = 1.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.upper_evidence_limit = 0.5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("upper_evidence_limit", "double", 0, "Limite superior de la evidencia (entre 0 y 1)", "", &getallfromHTPApublishedConfig::upper_evidence_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("upper_evidence_limit", "double", 0, "Limite superior de la evidencia (entre 0 y 1)", "", &getallfromHTPApublishedConfig::upper_evidence_limit)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.zoom_evidence = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.zoom_evidence = 100;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.zoom_evidence = 20;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("zoom_evidence", "int", 0, "Zoom de la imagen de evidencias", "", &getallfromHTPApublishedConfig::zoom_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("zoom_evidence", "int", 0, "Zoom de la imagen de evidencias", "", &getallfromHTPApublishedConfig::zoom_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.threshold_evidence = 0.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.threshold_evidence = 1.0;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.threshold_evidence = 0.5;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("threshold_evidence", "double", 0, "Threshold de las evidencias (entre 0 y 1)", "", &getallfromHTPApublishedConfig::threshold_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<double>("threshold_evidence", "double", 0, "Threshold de las evidencias (entre 0 y 1)", "", &getallfromHTPApublishedConfig::threshold_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.min_size_evidence = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.min_size_evidence = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.min_size_evidence = 2000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("min_size_evidence", "int", 0, "Tamanyo minimo del blob de las evidencias", "", &getallfromHTPApublishedConfig::min_size_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("min_size_evidence", "int", 0, "Tamanyo minimo del blob de las evidencias", "", &getallfromHTPApublishedConfig::min_size_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.max_size_evidence = 1;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.max_size_evidence = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.max_size_evidence = 1000000;
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("max_size_evidence", "int", 0, "Tamanyo maximo del blob de las evidencias", "", &getallfromHTPApublishedConfig::max_size_evidence)));
//#line 259 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr(new getallfromHTPApublishedConfig::ParamDescription<int>("max_size_evidence", "int", 0, "Tamanyo maximo del blob de las evidencias", "", &getallfromHTPApublishedConfig::max_size_evidence)));
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/groovy/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(getallfromHTPApublishedConfig::AbstractGroupDescriptionConstPtr(new getallfromHTPApublishedConfig::GroupDescription<getallfromHTPApublishedConfig::DEFAULT, getallfromHTPApublishedConfig>(Default)));
//#line 390 "/opt/ros/groovy/share/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<getallfromHTPApublishedConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<getallfromHTPApublishedConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    getallfromHTPApublishedConfig __max__;
    getallfromHTPApublishedConfig __min__;
    getallfromHTPApublishedConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const getallfromHTPApublishedConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static getallfromHTPApublishedConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &getallfromHTPApublishedConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const getallfromHTPApublishedConfig &getallfromHTPApublishedConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const getallfromHTPApublishedConfig &getallfromHTPApublishedConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const getallfromHTPApublishedConfig &getallfromHTPApublishedConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<getallfromHTPApublishedConfig::AbstractParamDescriptionConstPtr> &getallfromHTPApublishedConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<getallfromHTPApublishedConfig::AbstractGroupDescriptionConstPtr> &getallfromHTPApublishedConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const getallfromHTPApublishedConfigStatics *getallfromHTPApublishedConfig::__get_statics__()
  {
    const static getallfromHTPApublishedConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = getallfromHTPApublishedConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __GETALLFROMHTPAPUBLISHEDRECONFIGURATOR_H__
